### ISSUE TITLE
Syntax highlighting not applying correctly to .gvar files

### ISSUE THREAD

**Issue by Undeemiss** [Croebh/avrae-vscode#3]
Due to the fact that .gvar and .alias/.snippet files are treated identically, syntax highlighting only applies inside `<drac2>` blocks, even though gvars do not require <drac2> blocks. As a workaround, I have been adding a commented-out `<drac2>` at the top of my gvars, but this behavior is clearly undesirable.

I have included some relevant screenshots demonstrating current behavior in .gvar files below.

![image](https://github.com/Croebh/avrae-vscode/assets/55594961/3d12bb47-4617-4c03-8ecc-3ccc2bd784e4)
![image](https://github.com/Croebh/avrae-vscode/assets/55594961/82cd48df-622f-4659-b9ef-d6dd1bc60239)

**Comment by Croebh** [comment]
Amusingly I ran into this myself yesterday and performed the exact same
'hotfix'

Not entirely sure how to fix this atm, but *is* on my mind to fix

**Comment by Croebh** [comment]
Fixed in v0.2.0 https://github.com/Croebh/avrae-vscode/commit/df380b587d4f13bc4f5f78de30f35f601c578b89
