### ISSUE TITLE
Update GVAR and Get GVAR fail with 403 error

### ISSUE THREAD

**Issue by Undeemiss** [Croebh/avrae-vscode#4]
Having added my Avrae token to the extension, I attempted to use the `Avrae Utilities: Update GVAR` function from the command pallete. However, this resulted in nothing but a 403 error. I then attempted to use `Avrae Utilities: Get GVAR`, and it also gave a 403 error. Presumably, this extension is trying to use a deprecated API to accomplish these tasks.

I have included some screenshots of the full error message I received below:

![image](https://github.com/Croebh/avrae-vscode/assets/55594961/2963fb56-de68-4f69-bb36-a98229a550b6)
![image](https://github.com/Croebh/avrae-vscode/assets/55594961/97bef164-1d0d-4726-bb85-c4454eb7433d)

**Comment by Croebh** [comment]
Odd, it seems to function fine for me

[image: Code_kGt3D08dFd.gif]

**Comment by Croebh** [comment]
Odd, it seems to function fine for me

![Code_kGt3D08dFd](https://github.com/Croebh/avrae-vscode/assets/5848891/9467ef30-9e4e-4261-891b-4e82a98dc709)

**Comment by Undeemiss** [comment]
Perhaps there's a problem with my token, after all? I wasn't able to follow the steps for getting the token exactly due to using Firefox. I'll try again with Chrome and see if it gives me a different token.

**Comment by Undeemiss** [comment]
I just double-checked, and Chrome is yielding the same token that Firefox was. Presumably, our issue lies elsewhere.
I have tried both while connected directly over my home network and while using a VPN service, so presumably it isn't some sort of DNS issue on my side or my IP being blocked.

**Comment by Croebh** [comment]
And to be clear, your token that you saved in your settings is _just_ the token, no spaces at all or anything like that? Just 300 or so (might be longer or shorter, idr the spec on that token) of letters, numbers, and maybe some periods?

**Comment by Undeemiss** [comment]
That is correct. The token is alphanumeric with a few special characters, and somewhere around 300 characters in length. It contains no spaces, no quotation marks, etc.

**Comment by Croebh** [comment]
It seems to get it to respect any changes to your token right now, you have to reload the entire window (Ctrl+Shift+P to open the command pallet, `Developer: Reload Window`

So if you've made changes to ensure its correct, it may not be reading the settings

**Comment by Undeemiss** [comment]
Using `Developer: Reload Window` resolved the issue. Ideally, it would do this on its own, but I'm glad to see that it works with that change. Perhaps, if getting it to reload the window on its own is too difficult, the error could be intercepted and replaced with a new message stating the problem is most likely due to the token not being loaded, and to try `Developer: Reload Window`?

**Comment by Undeemiss** [comment]
I'll leave it up to you if you'd like to close this thread and have me open a new issue for this behavior or to leave this one as-is.

**Comment by Croebh** [comment]
I'm looking into better ways to do this in general, such as grabbing it
more regularly. This project was just me quickly throwing together a VS
Code extension at the request of the community. It hasn't been touched in a
few years, as I don't use VS Code regularly myself, and isn't on par with
the existing Sublime Text extension that I actively use (and developed,
though it too doesn't get a lot of updates)

Ideally I'd get them to be at the same state, but my JavaScript/TypeScript
skills are not nearly where my Python skills are at, so it's a bit more
trial and error, on top of my inexperience with the platform itself.

**Comment by Croebh** [comment]
As a note, 403 errors are usually Access Denied errors, so from the get go
I suspected it was an issue with your token. I just hadn't realized it
wasn't grabbing the updated setting at the too, haha

**Comment by Undeemiss** [comment]
You're so right; I was getting 403 and 404 errors mixed up in my head. I apologize for any confusion my attempts at pinpointing the issue may have caused.

**Comment by Croebh** [comment]
Its fine! Thank you for reporting these issues, its helping kick my butt back into developing the extension(s) :D

**Comment by Croebh** [comment]
Fixed in v0.2.0 https://github.com/Croebh/avrae-vscode/commit/3d19d3184fa3d1f8309f1493337e5edbc52b2481
